### ISSUE TITLE
前端或使用已有开源项目构建？

### ISSUE THREAD

**Issue by aboutmydreams** [pwh-pwh/ai-gui#2]
前端已经有不少支持大多数市面上模型的 chat ui 了，是不是可以考虑直接魔改一个嵌入 会快很多

**Comment by pwh-pwh** [comment]
项目的初衷是方便个人简单使用，且可以随时打开关闭，所以只是加了简单的问答功能，更像是一个辅助工具。市面上面的功能多，比较臃肿。我的开发理念是大道至简。用户可以当成一个悬浮记事本一样，一直挂着也不占用位置
